title: saranya's ap comp sci final project 
author: saranya g. 
email: saranya.guttikonda@gmail.com
description: this is a website about me that has my name, social media information, pciture, and brag sheet. 
github_slideshow: https://srnya11.github.io/github-pages-with-jekyll/
theme: minima

# social links
instagram_username: srnya.gttknda
email: saranya.guttikonda@gmail.com
github_username:  srnya11



show_excerpts: false
