title: saranya
author: saranya
email: saranya.guttikonda@gmail.com
description: this is a website about me :P
theme: minima

# social links
instagram_username: srnya.gttknda
github_username:  srnya11

show_excerpts: false
